from enum import StrEnum

from aiokafka.errors import (
    BrokerNotAvailableError,
    KafkaConnectionError,
    KafkaTimeoutError,
    LeaderNotAvailableError,
    NodeNotReadyError,
)

USER_SURNAME_MIN_LENGTH = 3
USER_SURNAME_MAX_LENGTH = 20

USER_NAME_MIN_LENGTH = 3
USER_NAME_MAX_LENGTH = 25

USER_USERNAME_MIN_LENGTH = 5
USER_USERNAME_MAX_LENGTH = 20

USER_EMAIL_MIN_LENGTH = 5
USER_EMAIL_MAX_LENGTH = 30

USER_PASSWORD_MIN_LENGTH = 8
USER_PASSWORD_MAX_LENGTH = 40

USER_ENCRYPTED_PASSWORD_MAX_LENGTH = 128

PROJECT_NAME_MIN_LENGTH = 5
PROJECT_NAME_MAX_LENGTH = 30

PROJECT_DESCRIPTION_MIN_LENGTH = 0
PROJECT_DESCRIPTION_MAX_LENGTH = 512

PROJECT_PAGINATION_SIZE_MIN_VALUE = 1
PROJECT_PAGINATION_PAGE_MIN_VALUE = 1

TAG_MIN_LENGTH = 3
TAG_MAX_LENGTH = 25

RENDER_WIDTH_MIN_VALUE = 20
RENDER_WIDTH_MAX_VALUE = 2160

RENDER_HEIGHT_MIN_VALUE = 20
RENDER_HEIGHT_MAX_VALUE = 3840

RENDER_SAMPLES_MIN_VALUE = 1
RENDER_SAMPLES_MAX_VALUE = 200


FILE_NAME_MIN_LENGTH = 3
FILE_NAME_MAX_LENGTH = 40

FILE_SIZE_MIN_VALUE_BYTES = 0
FILE_SIZE_MAX_VALUE_BYTES = 20 * 1024 * 1024
FILE_BUCKET_MAX_LENGTH = 25
FILE_KEY_MAX_LENGTH = 128

OUTBOX_TOPIC_MAX_LENGTH = 512


FIELD_SUB = "sub"
TOKEN_TYPE = "type"

BEARER_TOKEN_TYPE = "Bearer"
ACCESS_TOKEN_FIELD = "access"
REFRESH_TOKEN_FIELD = "refresh"

KAFKA_CONNECTION_ERROR = (
    KafkaConnectionError
    | KafkaTimeoutError
    | BrokerNotAvailableError
    | NodeNotReadyError
    | LeaderNotAvailableError
)


class EventStatus(StrEnum):
    pending = "pending"
    sent = "sent"


class RenderStatus(StrEnum):
    rendering = "rendering"
    completed = "completed"


class ProjectVisibility(StrEnum):
    public = "public"
    private = "private"
