"""add unique file path constraint

Revision ID: 2954f180ab5b
Revises: c237a3caa1ac
Create Date: 2026-09-22 11:16:57.734310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2954f180ab5b"
down_revision: Union[str, Sequence[str], None] = "c237a3caa1ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE files
        ADD CONSTRAINT uq_files_bucket_key UNIQUE (bucket, key)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE files
        DROP CONSTRAINT uq_files_bucket_key
        """
    )
    # ### end Alembic commands ###
